repos:
  # Hook untuk merapikan kode Python menggunakan Black
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        stages: [commit]

  # Hook tambahan untuk memeriksa file Python agar sesuai standar Flake8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0  # Versi terbaru Flake8
  #   hooks:
  #     - id: flake8
  #       stages: [commit]  # Periksa hanya file yang di-commit

  # Hook untuk memastikan commit message sesuai dengan konvensi tertentu
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
