repos:
  # Hook buat rapiin kode python lo
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        stages: [commit]

  # Hook buat ngecek file Python udah sesuai standar Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 
    hooks:
      - id: flake8
        stages: [commit] 

  # Hook buat ngecek commit message lo
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
